#ifndef _MONITOR_PROC_MONITOR_PATH_H_
#define _MONITOR_PROC_MONITOR_PATH_H_

/* 顶级目录和路径 */
#define MONITORY_FS_ENTRY_ROOT_NAME     "monitor"
#define MONITORY_FS_ENTRY_CPU_ROOT_NAME "cpu"
#define MONITORY_FS_ENTRY_MEM_ROOT_NAME "memory"

#define MONITOR_PROC_ROOT_PATH          "/proc/" MONITORY_FS_ENTRY_ROOT_NAME
#define MONITOR_PROC_CPU_ROOT_PATH      MONITOR_PROC_ROOT_PATH "/" MONITORY_FS_ENTRY_CPU_ROOT_NAME
#define MONITOR_PROC_MEM_ROOT_PATH      MONITOR_PROC_ROOT_PATH "/" MONITORY_FS_ENTRY_MEM_ROOT_NAME

/* 文件名约定 */
/* 历史刻度值 */
#define MONITOR_PROC_HIST_1MIN          "stat"
#define MONITOR_PROC_HIST_5MIN          "stat_hist_5min"
#define MONITOR_PROC_HIST_1HOUR         "stat_hist_1hour"
#define MONITOR_PROC_HIST_1DAY          "stat_hist_1day"

/* 实时更新值 */
#define MONITOR_PROC_RT_1MIN            "stat_rt_1min"
#define MONITOR_PROC_RT_5MIN            "stat_rt_5min"

/* 外部组件查询利用率信息文件 */
/* CPU使用率文件(各核总述) */
#define MONITOR_PROC_HIST_1MIN_PERCPU  MONITOR_PROC_CPU_ROOT_PATH "/" MONITOR_PROC_HIST_1MIN
#define MONITOR_PROC_HIST_5MIN_PERCPU  MONITOR_PROC_CPU_ROOT_PATH "/" MONITOR_PROC_HIST_5MIN
#define MONITOR_PROC_HIST_1HOUR_PERCPU MONITOR_PROC_CPU_ROOT_PATH "/" MONITOR_PROC_HIST_1HOUR
#define MONITOR_PROC_HIST_1DAY_PERCPU  MONITOR_PROC_CPU_ROOT_PATH "/" MONITOR_PROC_HIST_1DAY
#define MONITOR_PROC_RT_1MIN_PERCPU    MONITOR_PROC_CPU_ROOT_PATH "/" MONITOR_PROC_RT_1MIN
#define MONITOR_PROC_RT_5MIN_PERCPU    MONITOR_PROC_CPU_ROOT_PATH "/" MONITOR_PROC_RT_5MIN

/* 内存使用率文件(总述) */
#define MONITOR_PROC_HIST_1MIN_MEMORY  MONITOR_PROC_MEM_ROOT_PATH "/" MONITOR_PROC_HIST_1MIN
#define MONITOR_PROC_HIST_5MIN_MEMORY  MONITOR_PROC_MEM_ROOT_PATH "/" MONITOR_PROC_HIST_5MIN
#define MONITOR_PROC_HIST_1HOUR_MEMORY MONITOR_PROC_MEM_ROOT_PATH "/" MONITOR_PROC_HIST_1HOUR
#define MONITOR_PROC_HIST_1DAY_MEMORY  MONITOR_PROC_MEM_ROOT_PATH "/" MONITOR_PROC_HIST_1DAY

/* 任务信息相关 */
/* task cpu, thread only */

/* task memory, process only */

#endif /* _MONITOR_PROC_MONITOR_PATH_H_ */
