#ifndef _MONITOR_PROC_MONITOR_PATH_H_
#define _MONITOR_PROC_MONITOR_PATH_H_

/* 顶级目录和路径 */
#define MONITORY_FS_ENTRY_ROOT_NAME     "monitor"
#define MONITORY_FS_ENTRY_CPU_ROOT_NAME "cpu"
#define MONITORY_FS_ENTRY_MEM_ROOT_NAME "memory"
#define MONITORY_FS_ENTRY_TSK_ROOT_NAME "task"

#define MONITOR_PROC_ROOT_PATH          "/proc/" MONITORY_FS_ENTRY_ROOT_NAME
#define MONITOR_PROC_CPU_ROOT_PATH      MONITOR_PROC_ROOT_PATH "/" MONITORY_FS_ENTRY_CPU_ROOT_NAME
#define MONITOR_PROC_MEM_ROOT_PATH      MONITOR_PROC_ROOT_PATH "/" MONITORY_FS_ENTRY_MEM_ROOT_NAME
#define MONITOR_PROC_TASK_ROOT_PATH     MONITOR_PROC_ROOT_PATH "/" MONITORY_FS_ENTRY_TSK_ROOT_NAME

/* 文件名约定 */
/* 历史刻度值 */
#define MONITOR_PROC_HIST_1MIN          "stat"
#define MONITOR_PROC_HIST_5MIN          "stat_hist_5min"
#define MONITOR_PROC_HIST_1HOUR         "stat_hist_1hour"
#define MONITOR_PROC_HIST_1DAY          "stat_hist_1day"

/* 实时更新值 */
#define MONITOR_PROC_RT_1MIN            "stat_rt_1min"
#define MONITOR_PROC_RT_5MIN            "stat_rt_5min"

/* 外部组件查询利用率信息文件 */
/* CPU使用率文件(各核总述)
 * 格式：cpu编号  当前时间段内统计平均值 历史值1 历史值2 ... 历史值n
 */
#define MONITOR_PROC_HIST_1MIN_PERCPU  MONITOR_PROC_CPU_ROOT_PATH "/" MONITOR_PROC_HIST_1MIN
#define MONITOR_PROC_HIST_5MIN_PERCPU  MONITOR_PROC_CPU_ROOT_PATH "/" MONITOR_PROC_HIST_5MIN
#define MONITOR_PROC_HIST_1HOUR_PERCPU MONITOR_PROC_CPU_ROOT_PATH "/" MONITOR_PROC_HIST_1HOUR
#define MONITOR_PROC_HIST_1DAY_PERCPU  MONITOR_PROC_CPU_ROOT_PATH "/" MONITOR_PROC_HIST_1DAY
#define MONITOR_PROC_RT_1MIN_PERCPU    MONITOR_PROC_CPU_ROOT_PATH "/" MONITOR_PROC_RT_1MIN
#define MONITOR_PROC_RT_5MIN_PERCPU    MONITOR_PROC_CPU_ROOT_PATH "/" MONITOR_PROC_RT_5MIN

/* 内存使用率文件(总述)
 * 格式：当前时间段内统计平均值 历史值1 历史值2 ... 历史值n
 */
#define MONITOR_PROC_HIST_1MIN_MEMORY  MONITOR_PROC_MEM_ROOT_PATH "/" MONITOR_PROC_HIST_1MIN
#define MONITOR_PROC_HIST_5MIN_MEMORY  MONITOR_PROC_MEM_ROOT_PATH "/" MONITOR_PROC_HIST_5MIN
#define MONITOR_PROC_HIST_1HOUR_MEMORY MONITOR_PROC_MEM_ROOT_PATH "/" MONITOR_PROC_HIST_1HOUR
#define MONITOR_PROC_HIST_1DAY_MEMORY  MONITOR_PROC_MEM_ROOT_PATH "/" MONITOR_PROC_HIST_1DAY

/* 任务信息相关 */
/* 入口，分两类： 进程、线程 */
#define MONITOR_PROC_TASK_RPOCESS_NAME  "process"
#define MONITOR_PROC_TASK_THREAD_NAME   "thread"
#define MONITOR_PROC_TASK_STATUS_NAME   "status"

#define MONITOR_PROC_TASK_RPOCESS_ROOT  MONITOR_PROC_TASK_ROOT_PATH "/" MONITOR_PROC_TASK_RPOCESS_NAME
#define MONITOR_PROC_TASK_THREAD_ROOT   MONITOR_PROC_TASK_ROOT_PATH "/" MONITOR_PROC_TASK_THREAD_NAME
/* 任务状态
 * 进程的格式：进程id 父进程id 状态 优先级 nice rt优先级* 调度方式* cpu cpu列表 启动时间
 * 线程的格式：线程id 主线程id 状态 优先级 nice rt优先级* 调度方式* cpu cpu列表 启动时间
 */
#define MONITOR_PROC_TASK_RPOCESS_STATUS MONITOR_PROC_TASK_RPOCESS_ROOT "/" MONITOR_PROC_TASK_STATUS_NAME
#define MONITOR_PROC_TASK_THREAD_STATUS  MONITOR_PROC_TASK_THREAD_ROOT "/" MONITOR_PROC_TASK_STATUS_NAME

/* 任务的CPU利用率统计，只统计线程
 * 格式：线程id cpu 当前时间段内统计平均值 历史值1 历史值2 ... 历史值n
 */
#define MONITOR_PROC_TASK_1MIN_CPU  MONITOR_PROC_TASK_THREAD_ROOT "/" MONITOR_PROC_HIST_1MIN
#define MONITOR_PROC_TASK_5MIN_CPU  MONITOR_PROC_TASK_THREAD_ROOT "/" MONITOR_PROC_HIST_5MIN
#define MONITOR_PROC_TASK_1HOUR_CPU MONITOR_PROC_TASK_THREAD_ROOT "/" MONITOR_PROC_HIST_1HOUR
#define MONITOR_PROC_TASK_1DAY_CPU  MONITOR_PROC_TASK_THREAD_ROOT "/" MONITOR_PROC_HIST_1DAY

/* 任务的内存利用率统计，只统计进程
 * 格式：进程pid 当前时间段内统计平均值 历史值1 历史值2 ... 历史值n
 */
#define MONITOR_PROC_TASK_1MIN_MEM  MONITOR_PROC_TASK_RPOCESS_ROOT "/" MONITOR_PROC_HIST_1MIN
#define MONITOR_PROC_TASK_5MIN_MEM  MONITOR_PROC_TASK_RPOCESS_ROOT "/" MONITOR_PROC_HIST_5MIN
#define MONITOR_PROC_TASK_1HOUR_MEM MONITOR_PROC_TASK_RPOCESS_ROOT "/" MONITOR_PROC_HIST_1HOUR
#define MONITOR_PROC_TASK_1DAY_MEM  MONITOR_PROC_TASK_RPOCESS_ROOT "/" MONITOR_PROC_HIST_1DAY

#endif /* _MONITOR_PROC_MONITOR_PATH_H_ */
